const newsData_en = [
  {
    "cat": "Politics",
    "title": "Manipur at crossroads after BJP names new CM amid ethnic crisis",
    "desc": "After nearly a year under President’s Rule, Manipur takes a key step towards restoring an elected government with BJP MLA Yumnam Khemchand Singh set to become Chief Minister. The leadership change carries major implications for peace, governance, and reconciliation in the State.",
    "img": "https://th-i.thgim.com/public/incoming/ygxqcc/article70590229.ece/alternates/LANDSCAPE_1200/manipur1.jpg",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/videos/watch-manipur-at-crossroads-after-bjp-names-new-cm-amid-ethnic-crisis/article70590233.ece",
    "time": "2026-02-04T04:20:56.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "Mumbai Police warns of 'masked guests'",
    "desc": "Mumbai Police has taken a creative leap, stepping into the shoes of Lady Whistledown from 'Bridgerton' to bring attention to online safety. Their engaging social media campaigns, echoing the dramatic flair of the award-winning series, caution the public against lurking 'masked guests' in cyberspace.",
    "img": "https://static.toiimg.com/photo/msid-127899492,imgsize-34980.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/hindi/bollywood/news/mumbai-police-joins-bridgerton-season-4-trend-channels-lady-whistledown-to-warn-citizen-of-masked-guests/articleshow/127899101.cms",
    "time": "2026-02-04T04:11:22.000Z"
  },
  {
    "cat": "Business",
    "title": "Infosys, TCS, Wipro down up to 6%",
    "desc": "Shares of major IT companies, including Infosys, Wipro, HCL Tech and Persistent Systems, slid as much as 6 per cent in early trade. The negative sentiment mirrored weakness on Wall Street, where the technology-heavy benchmark Nasdaq declined 1.4 per cent, erasing nearly $300 billion in market capitalisation across the sector.",
    "img": "https://static.toiimg.com/photo/msid-127899423,imgsize-128926.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/indian-it-stocks-crash-infosys-tcs-wipro-down-up-to-6-why-launch-of-new-ai-tool-by-us-startup-anthropic-is-driving-the-fall/articleshow/127899406.cms",
    "time": "2026-02-04T04:06:48.000Z"
  },
  {
    "cat": "Politics",
    "title": "SIT finds ‘serious irregularities, deliberate misconduct’ in TTD adulterated ghee case",
    "desc": "Highlighting the role of the TTD Purchase Committee in the alleged episode, the probe team flags the role of Chevireddy Bhaskar Reddy, Bhumana Karunakar Reddy, and senior officials Anil Kumar Singhal, A.V. Dharma Reddy, and O. Balaji in the case",
    "img": "https://th-i.thgim.com/public/incoming/9yb87l/article70590197.ece/alternates/LANDSCAPE_1200/21GNRAO-TIRUMALA%20LADDU-01%202.JPG",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/national/andhra-pradesh/sit-finds-serious-irregularities-deliberate-misconduct-in-ttd-adulterated-ghee-case/article70588560.ece",
    "time": "2026-02-04T04:04:11.000Z"
  },
  {
    "cat": "Politics",
    "title": "364 Maoists, including 12 top leaders, killed last year; 2,337 surrendered",
    "desc": "Security forces neutralized 364 Naxals, arrested 1,022, and saw 2,337 surrender last year as Left-wing extremism incidents dropped significantly. The number of affected districts has fallen to 32 from 61 since 2019, with a substantial dip in violence and casualties. The government aims to eradicate Naxalism by March 31, 2026.",
    "img": "https://static.toiimg.com/photo/msid-127899256,imgsize-998450.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/india/mha-364-maoists-including-12-top-leaders-killed-last-year-2337-surrendered/articleshow/127899198.cms",
    "time": "2026-02-04T03:49:32.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "Salman playing Bade Sahab in film?",
    "desc": "Speculation is rife about Salman Khan joining the cast of 'Dhurandhar 2', with viral images suggesting his involvement as 'Bade Sahab'. However, these pictures are reportedly AI-generated by an artist, sparking mixed reactions online. The espionage thriller, starring Ranveer Singh, is slated for a March 2026 release. Read on to know more.",
    "img": "https://static.toiimg.com/photo/msid-127899219,imgsize-33002.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/hindi/bollywood/news/dhurandhar-2-fact-check-is-salman-khan-playing-bade-sahab-in-the-ranveer-singh-starrer-viral-pictures-spark-speculation/articleshow/127899219.cms",
    "time": "2026-02-04T03:48:46.000Z"
  },
  {
    "cat": "Politics",
    "title": "Reverse migration seen in Arunachal’s ‘vibrant villages’",
    "desc": "Arunachal Pradesh villages along the China border are witnessing reverse migration, a positive sign for the Vibrant Villages Programme. The initiative, aimed at boosting living conditions and livelihoods, has seen significant investment. Over 8,500 activities were conducted nationwide, with Arunachal Pradesh receiving the largest share of funds for development projects.",
    "img": "https://static.toiimg.com/photo/msid-127899159,imgsize-1596203.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/india/mha-reverse-migration-seen-in-arunachals-vibrant-villages/articleshow/127899119.cms",
    "time": "2026-02-04T03:42:00.000Z"
  },
  {
    "cat": "Sports",
    "title": "India's top-order firepower will be hard to match at T20 World Cup",
    "desc": "T20 cricket's Powerplay scoring has dramatically increased, with teams now targeting 75 runs for a strong start. India's explosive openers, led by Abhishek Sharma, are setting new benchmarks. While other nations like England, New Zealand, and Australia also boast formidable opening pairs, India's aggressive approach, featuring a potential all-left-handed top order, promises thrilling encounters.",
    "img": "https://static.toiimg.com/photo/msid-127899127,imgsize-75214.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/icc-mens-t20-world-cup/powerplay-warriors-indias-explosive-top-order-firepower-will-be-hard-to-match-at-t20-world-cup/articleshow/127899078.cms",
    "time": "2026-02-04T03:36:23.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "Chris Hemsworth opens up about his ‘safety net’ character",
    "desc": "Chris Hemsworth shares that stepping into the shoes of Thor became his 'refuge' during the tough beginnings of his career in Hollywood, a phase filled with self-doubt and panic attacks. He acknowledges that the confident exterior he portrays is often a crafted facade, differing from his more vulnerable reality.",
    "img": "https://static.toiimg.com/photo/msid-127899118,imgsize-63560.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/english/hollywood/news/chris-hemsworth-reveals-playing-thor-was-his-safety-net-in-early-hollywood-career/articleshow/127899107.cms",
    "time": "2026-02-04T03:35:10.000Z"
  },
  {
    "cat": "Politics",
    "title": "Taking on the C-word, with jokes and joy",
    "desc": "A new play, 'Breast of Luck,' co-written by a cancer survivor and a caregiver, uses song, dance, and humor to navigate the grim realities of illness. The musical comedy, inspired by personal experiences, highlights the therapeutic power of laughter, community, and art in confronting cancer, offering a lighter perspective on a serious topic.",
    "img": "https://static.toiimg.com/photo/msid-127899073,imgsize-944096.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/india/taking-on-the-c-word-with-jokes-and-joy/articleshow/127898956.cms",
    "time": "2026-02-04T03:30:22.000Z"
  },
  {
    "cat": "Sports",
    "title": "Pakistan's boycott of T20 World Cup match vs India: How PCB is 'violating' contract and ICC Terms of Participation",
    "desc": "Pakistan’s decision to boycott only its T20 World Cup match against India has put the PCB on a collision course with the ICC. With no force majeure clause in the participation agreement, the move is being viewed as a contractual violation. The ICC is likely to question selective participation and potential government interference, with sanctions not ruled out.",
    "img": "https://static.toiimg.com/photo/msid-127898545,imgsize-93786.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/icc-mens-t20-world-cup/pakistans-boycott-of-t20-world-cup-match-vs-india-how-pcb-is-violating-contract-and-icc-terms-of-participation/articleshow/127898401.cms",
    "time": "2026-02-04T03:26:00.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "'I am not active there'",
    "desc": "Acclaimed filmmaker Jeethu Joseph shared his approach to online negativity, stating he disregards insults from fake IDs, preferring honest feedback. He revealed that his team alerted him to such attacks, which he believes are common among public figures. Joseph, drawing from his farmer background, views opposition as a natural part of life's journey, focusing instead on constructive criticism.",
    "img": "https://static.toiimg.com/photo/msid-127898819,imgsize-42240.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/malayalam/movies/news/jeethu-joseph-says-fake-id-attacks-do-not-bother-him-i-have-grown-up-seeing-everything-in-life/articleshow/127898819.cms",
    "time": "2026-02-04T03:13:20.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "Priyanka's demand made Mahesh face consequences",
    "desc": "Priyanka Chopra makes a highly anticipated comeback to Indian cinema with SS Rajamouli's epic 'Varanasi', where she portrays the enchanting Mandakini. Impressively, her only condition for taking on the role was to be part of a lively dance sequence, resulting in an ambitious filming process.",
    "img": "https://static.toiimg.com/photo/msid-127898764,imgsize-46210.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/telugu/movies/news/varanasi-priyanka-chopras-one-demand-to-ss-rajamouli-for-coming-on-board-made-mahesh-babu-bear-the-consequences/articleshow/127898764.cms",
    "time": "2026-02-04T03:10:48.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "Miranda Kerr on her relationship with ex Orlando Bloom",
    "desc": "Miranda Kerr, the renowned supermodel, shared an honest reflection on her relationship with Orlando Bloom, noting that their marriage didn't quite align with their individual journeys. Acknowledging their choice to amicably separate, she highlighted the importance of fostering a supportive environment for their son Flynn.",
    "img": "https://static.toiimg.com/photo/msid-127898731,imgsize-66270.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/english/hollywood/news/miranda-kerr-admits-she-and-ex-orlando-bloom-didnt-bring-out-the-best-in-each-other-in-a-new-revelation/articleshow/127898712.cms",
    "time": "2026-02-04T03:04:53.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "'Frozen 3' officially in the works: Josh Gad’s Insta post sparks excitement",
    "desc": "Fans are buzzing as 'Frozen 3' production is confirmed, with Josh Gad sharing an exciting behind-the-scenes photo. Disney CEO Bob Iger previously announced the sequel, and Jennifer Lee is set to direct. The film is slated for a November 24, 2027 theatrical release, with the original voice cast reportedly securing record-breaking deals.",
    "img": "https://static.toiimg.com/photo/msid-127898713,imgsize-799050.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/web-series/news/english/time-to-build-another-snowman-josh-gad-hints-at-frozen-3-release-planned-for-2027/articleshow/127898720.cms",
    "time": "2026-02-04T03:03:21.000Z"
  },
  {
    "cat": "Sports",
    "title": "Dhoni backs India as T20 World Cup favourites but flags his biggest concern",
    "desc": "Legendary captain MS Dhoni rates India as a formidable contender for the T20 World Cup, citing their immense experience and current form. However, he expressed concern over the impact of dew, which can significantly influence match outcomes. Dhoni also emphasized the inherent unpredictability of T20 cricket, where individual brilliance and player availability are crucial for success.",
    "img": "https://static.toiimg.com/photo/msid-127898671,imgsize-63422.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/icc-mens-t20-world-cup/one-of-the-most-dangerous-teams-ms-dhoni-backs-india-as-t20-world-cup-favourites-but-flags-his-biggest-concern/articleshow/127898623.cms",
    "time": "2026-02-04T03:00:48.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "Cardi B's daughter takes on bug sis duties for baby brother",
    "desc": "Cardi B is fully embracing her new role as a mother of two, with her 16-month-old daughter Blossom lovingly doting on her baby brother. While she treasures these intimate family interactions, Cardi is choosing to keep her son’s details, including his name, a mystery—consistent with her privacy strategy for her other kids.",
    "img": "https://static.toiimg.com/photo/msid-127898600,imgsize-506874.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/english/music/news/cardi-b-shares-adorable-moment-of-daughter-blossom-taking-up-on-big-sister-duties-for-her-baby-brother/articleshow/127898600.cms",
    "time": "2026-02-04T02:58:49.000Z"
  },
  {
    "cat": "Business",
    "title": "Stock recommendations for February 4, 2026",
    "desc": "According to Mehul Kothari, DVP - Technical Research, Anand Rathi Shares and Stock Brokers, the top stocks to buy today (February 4, 2026) are Indian Oil Corporation, Tata Elxsi, and IFCI. Let’s take a look:",
    "img": "https://static.toiimg.com/photo/msid-127898318,imgsize-80478.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/top-stock-recommendations-for-february-04-2026-india-oil-corporation-tata-elxsi-ifci-best-stocks-to-buy-today/articleshow/127898283.cms",
    "time": "2026-02-04T02:40:03.000Z"
  },
  {
    "cat": "Business",
    "title": "Nukes, defence, minerals: Inside Jaishankar-Rubio talks post India-US trade deal",
    "desc": "External affairs minister S Jaishankar met US Secretary of State Marco Rubio in Washington, discussing expanded bilateral and multilateral cooperation, including through the Quad. The talks covered trade, defense, critical minerals, and energy, following a recently finalized trade deal. Both leaders emphasized strengthening economic ties and ensuring a prosperous Indo-Pacific region.",
    "img": "https://static.toiimg.com/photo/msid-127898293,imgsize-897075.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/nukes-defence-minerals-inside-jaishankar-rubio-talks-post-india-us-trade-deal/articleshow/127898160.cms",
    "time": "2026-02-04T02:39:00.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "Shot 'Varanasi' in IMAX for Ramayana scene",
    "desc": "Filmmaker SS Rajamouli reveals his upcoming magnum opus, 'Varanasi,' was filmed in IMAX to capture its grand scale, including portions set in Antarctica and the Ramayana era. He also shared a memorable interaction with James Cameron, who encouraged him to continue making films his way.",
    "img": "https://static.toiimg.com/photo/msid-127897914,imgsize-31822.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/hindi/bollywood/news/ss-rajamouli-reveals-he-filmed-varanasi-in-imax-for-ramayana-battle-scene/articleshow/127897715.cms",
    "time": "2026-02-04T02:25:57.000Z"
  },
  {
    "cat": "Sports",
    "title": "Indispensable! Why Axar Patel remains India’s unsung MVP",
    "desc": "Axar Patel’s career has been shaped by injuries, patience, and quiet excellence. From missing the 2023 ODI World Cup to starring in India’s 2024 T20 triumph, the all-rounder has grown into a vital cog across formats. Understated yet indispensable, a lot will depend on Axar's all-round skillsets in India's T20 World Cup title defence, starting from February 7.",
    "img": "https://static.toiimg.com/photo/msid-127898028,imgsize-52072.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/icc-mens-t20-world-cup/understated-indispensable-why-axar-patel-remains-indias-unsung-mvp/articleshow/127897912.cms",
    "time": "2026-02-04T02:20:06.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "Rashmika hints at February 26 wedding",
    "desc": "Speculation is rife about Rashmika Mandanna and Vijay Deverakonda's wedding, with fans believing February 26th is the confirmed date. A recent airport video, where Rashmika's reaction to wedding congratulations was interpreted as an indirect confirmation, has fueled these rumors. This follows earlier denials of a February 2nd wedding.",
    "img": "https://static.toiimg.com/photo/msid-127897971,imgsize-48504.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/telugu/movies/news/fans-react-rashmika-mandanna-indirectly-says-yes-to-february-26-wedding-with-vijay-deverakonda/articleshow/127897829.cms",
    "time": "2026-02-04T02:15:18.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "Sunny and Akshaye to FACE OFF against each other in 'Ikka'",
    "desc": "In an exciting comeback, powerhouse actors Sunny Deol and Akshaye Khanna are set to dominate the streaming world with their riveting courtroom thriller 'Ikka'. Slated for 2026, this film escalates into a fierce showdown, featuring Deol as a formidable defense attorney and Khanna as his relentless adversary, ensuring a nail-biting legal duel that audiences won't forget.",
    "img": "https://static.toiimg.com/photo/msid-127897860,imgsize-24556.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/hindi/bollywood/news/border-2-actor-sunny-deol-and-dhurandhar-star-akshaye-khanna-to-reunite-for-the-movie-ikka-witness-the-ultimate-face-off/articleshow/127897860.cms",
    "time": "2026-02-04T02:11:08.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "‘Heated Rivalry’ season 2 heats up with renewal buzz",
    "desc": "Fans eagerly await 'Heated Rivalry' Season 2, with filming slated for July or August, hinting at a late 2026 or early 2027 premiere. Hudson Williams and Connor Storrie return as hockey rivals Shane Hollander and Ilya Rozanov, exploring their forbidden romance and deeper dynamics. The new season adapts 'The Long Game' and 'Role Model' from Rachel Reid's book series.",
    "img": "https://static.toiimg.com/photo/msid-127897896,imgsize-749619.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/web-series/news/english/heated-rivalry-season-2-builds-momentum-with-renewal-return-cast-and-release-buzz/articleshow/127897904.cms",
    "time": "2026-02-04T02:06:09.000Z"
  },
  {
    "cat": "Politics",
    "title": "Wingtips of Air India, IndiGo planes touch each other at Mumbai airport",
    "desc": "An Air India spokesperson said flight AI2732 operating from Mumbai to Coimbatore was delayed after the aircraft scheduled to operate the service came into contact with another airline's aircraft while waiting on the taxiway prior to take-off",
    "img": "https://th-i.thgim.com/public/incoming/2508ut/article70590052.ece/alternates/LANDSCAPE_1200/PTI02_03_2026_000466B.jpg",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/national/wingtips-of-air-india-indigo-planes-touch-each-other-at-mumbai-airport/article70590051.ece",
    "time": "2026-02-04T01:58:06.000Z"
  },
  {
    "cat": "Business",
    "title": "‘A reset and fresh start’: India–China bilateral trade hits record $155 billion",
    "desc": "Bilateral trade between India and China reached a record $155 billion in 2025, marking over 12% year-on-year growth. Chinese Ambassador Xu Feihong highlighted this achievement, alongside support for India's BRICS presidency and a commitment to advancing the Global South's development agenda.",
    "img": "https://static.toiimg.com/photo/msid-127897821,imgsize-80810.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/a-reset-and-fresh-start-indiachina-bilateral-trade-hits-record-155-billion/articleshow/127897737.cms",
    "time": "2026-02-04T01:56:59.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "Tongva Tribe responds to new claims regarding Billie Eilish’s home",
    "desc": "Grammy winner Billie Eilish's comment about \"stolen land\" has drawn a response from the Tongva tribe. They confirmed her Los Angeles home is indeed on their ancestral territory, though Eilish has not directly contacted them. The tribe aims to educate and foster dialogue, reminding everyone that the Los Angeles basin remains Tongva land.",
    "img": "https://static.toiimg.com/photo/msid-127897798,imgsize-.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/english/music/news/billie-eilishs-home-is-on-tongva-tribe-ancestral-ground-her-stolen-land-remark-stirs-further-buzz/articleshow/127897798.cms",
    "time": "2026-02-04T01:53:49.000Z"
  },
  {
    "cat": "World",
    "title": "Kremlin warns of ‘dangerous’ moment as U.S.-Russia nuclear treaty set to expire",
    "desc": "New START, the last nuclear treaty between Washington and Moscow after decades of agreements dating to the Cold War, is set to expire on February 5, 2026, and with it restrictions on the two top nuclear powers",
    "img": "https://th-i.thgim.com/public/incoming/r4ul0b/article70589309.ece/alternates/LANDSCAPE_1200/2026-01-30T060033Z_1848011842_RC2V7GAKUYU1_RTRMADP_3_RUSSIA-USA-NUCLEAR.JPG",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/international/kremlin-warns-of-dangerous-moment-as-us-russia-nuclear-treaty-set-to-expire/article70589305.ece",
    "time": "2026-02-04T01:50:06.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "‘Bridgerton Season 4’ sparks buzz over modern band-aid slip",
    "desc": "Fans of 'Bridgerton Season 4' spotted a modern Band-Aid on actress Katie Leung's ear in the premiere episode, a detail jarringly out of place in the Regency setting. The discovery quickly went viral on social media, sparking humorous commentary. Despite this minor slip-up, the season focuses on Benedict Bridgerton's romance with Sophie Baek, promising steamy tension and societal drama.",
    "img": "https://static.toiimg.com/photo/msid-127897728,imgsize-622945.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/web-series/news/english/bridgerton-season-4-faces-scrutiny-after-modern-band-aid-breaks-regency-illusion/articleshow/127897734.cms",
    "time": "2026-02-04T01:38:59.000Z"
  },
  {
    "cat": "Politics",
    "title": "No death sentences confirmed by Supreme Court for third consecutive year",
    "desc": "Supreme Court acquits ten death row prisoners in 2025; despite “growing judicial scepticism” at higher levels, Sessions Courts handed down 1,310 death sentences over the last decade; high rate of acquittals raises concerns about wrongful convictions",
    "img": "https://th-i.thgim.com/public/incoming/cvx2pq/article70590025.ece/alternates/LANDSCAPE_1200/11_UNNAO_RAPE_CASE_HEARING_SUPREME_COURT_29_12_DELHI.jpg",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/national/no-death-sentences-confirmed-by-supreme-court-for-third-consecutive-year/article70587497.ece",
    "time": "2026-02-04T01:38:21.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "'You do not deserve to be bullied'",
    "desc": "Singer Abhirami Suresh bravely addressed online abuse following a live performance, sharing her years of bullying experiences. She emphasized that strength isn't silence and encouraged those facing similar pain, reminding them they are not alone. Fans rallied in support, praising her performance and honesty, offering love and encouragement.",
    "img": "https://static.toiimg.com/photo/msid-127897681,imgsize-.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/malayalam/movies/news/abhirami-suresh-faces-online-abuse-after-live-show-singer-says-you-do-not-deserve-to-be-bullied/articleshow/127897681.cms",
    "time": "2026-02-04T01:37:31.000Z"
  },
  {
    "cat": "World",
    "title": "Trump calls Colombia's Petro ‘terrific’ just weeks after insulting him as a ‘sick man’",
    "desc": "Donald Trump said afterwards that he and Gustavo Petro had not been \"the best of friends,\" suggesting that he had felt insulted by the President of Colombia because he did not know him and because the two had never met",
    "img": "https://th-i.thgim.com/public/incoming/i5gjdk/article70590030.ece/alternates/LANDSCAPE_1200/2026-02-03T175310Z_426447830_RC2HEJAUWQD7_RTRMADP_3_USA-TRUMP-COLOMBIA.JPG",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/international/trump-calls-colombias-petro-terrific-just-weeks-after-insulting-him-as-a-sick-man/article70590028.ece",
    "time": "2026-02-04T01:29:38.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "Sai Pallavi in race to replace Deepika; Kalki 2 makers CONFIRM",
    "desc": "Rumors about Sai Pallavi stepping in for Deepika Padukone in the sequel of 'Kalki 2898 AD' have caught the attention of fans, yet the film’s producers have clarified that no final decisions have been made. They are reportedly eyeing Sai Pallavi for the role of SUM-80, convinced that her talent aligns beautifully with the character's essence.",
    "img": "https://static.toiimg.com/photo/msid-127897608,imgsize-.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/telugu/movies/news/kalki-2-makers-confirm-sai-pallavi-being-considered-as-deepika-padukones-replacement-shell-be-a-perfect-fit/articleshow/127897608.cms",
    "time": "2026-02-04T01:25:36.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "Nelson Peltz speaks as the Beckham family feud intensifies",
    "desc": "Billionaire Nelson Peltz publicly praised son-in-law Brooklyn Beckham, emphasizing his desire for the couple's \"long, happy marriage.\" This comes after Brooklyn's explosive Instagram post detailing alleged parental interference and pressure. The Peltz family's public support for Brooklyn and Nicola, coupled with the Beckhams' silence, highlights a deepening rift.",
    "img": "https://static.toiimg.com/photo/msid-127897519,imgsize-650858.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/english/hollywood/news/nicola-peltz-dad-nelson-peltz-breaks-silence-amid-beckhampeltz-family-rift-want-them-to-enjoy-a-long-happy-marriage/articleshow/127897522.cms",
    "time": "2026-02-04T01:04:34.000Z"
  },
  {
    "cat": "Politics",
    "title": "India, US press ahead with deal but challenges remain",
    "desc": "The first is the India-Pakistan re-hyphenation Trump has brought upon India through his courting of Rawalpindi. It is here US ambassador to India Sergio Gor, who seems to have found a way out of the trade impasse within weeks of arrival, may have an important role to play. Suspense still looms over his dual role as Trump’s special envoy for south Asia and any false move bracketing India with Pakistan, let alone playing sheriff, will be met with resistance.",
    "img": "https://static.toiimg.com/photo/msid-127897462,imgsize-39826.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/india/india-us-press-ahead-with-deal-but-challenges-remain/articleshow/127897451.cms",
    "time": "2026-02-04T00:52:05.000Z"
  },
  {
    "cat": "Politics",
    "title": "Wipro’s stand on dispute over ex gratia with ex-staffer abuse of law, says HC, imposes costs",
    "desc": "​​In recognition of his contribution, he was offered an ex gratia lump sum amount of Rs 6,32,000, payable after 18 months from the date of cessation of employment, subject to the condition that from the date of cessation he would not join competing companies, namely Philips India Limited or Bajaj Electricals Ltd.",
    "img": "https://static.toiimg.com/photo/msid-127897422,imgsize-64602.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/india/wipros-stand-on-dispute-over-ex-gratia-with-ex-staffer-abuse-of-law-says-hc-imposes-costs/articleshow/127897433.cms",
    "time": "2026-02-04T00:44:56.000Z"
  },
  {
    "cat": "Politics",
    "title": "Wooing voters on caste, religion lines no ground to bar party: HC",
    "desc": "A division bench of Justice Rajan Roy and Justice AK Chaudhary passed the verdict on a PIL filed by Motilal Yadav in 2013, seeking direction against holding of caste-based rallies by political parties. In an interim order in July 2013 itself, a bench of Justice Uma Nath Singh and Justice Mahendra Dayal had stayed caste-based rallies “with immediate effect” throughout UP.",
    "img": "https://static.toiimg.com/photo/msid-127897374,imgsize-24002.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/india/wooing-voters-on-caste-religion-lines-no-ground-to-bar-party-hc/articleshow/127897242.cms",
    "time": "2026-02-04T00:34:33.000Z"
  },
  {
    "cat": "Politics",
    "title": "HC",
    "desc": "A bench headed by Chief Justice Ramesh Sinha held that the family court’s order showed no illegality or defect warranting interference by the HC. The HC noted that when the husband had filed a petition seeking restitution of conjugal rights, the woman could have returned to her matrimonial home to resume marital life.",
    "img": "https://static.toiimg.com/photo/msid-127897294,imgsize-87616.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/india/woman-not-entitled-to-maintenance-if-living-apart-sans-valid-reason-hc/articleshow/127897296.cms",
    "time": "2026-02-04T00:13:43.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "Film crosses Rs 286 cr amid decline",
    "desc": "'Border 2' has made waves at the box office, raking in an impressive Rs 286.75 crore domestically and a staggering Rs 392.5 crore internationally. This gripping war drama, following in the footsteps of its 1997 predecessor, has experienced a slight downturn in attendance on its eleventh day but continues to captivate audiences.",
    "img": "https://static.toiimg.com/photo/msid-127897236,imgsize-45794.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/entertainment/hindi/bollywood/news/border-2-box-office-collection-day-12-sunny-deol-and-varun-dhawan-starrer-sails-past-rs-286-crore-amid-steady-decline/articleshow/127897236.cms",
    "time": "2026-02-04T00:03:17.000Z"
  },
  {
    "cat": "Politics",
    "title": "Judges reserving verdicts for years ‘an ailment’: Supreme Court",
    "desc": "A litigant who approaches the court must get to know what judgment is given on his plea,” the CJI said. The same HC judge, Justice Rongon Mukhopadhyay, was found to have kept several judgments pending for years, even in cases where the convicts had appealed against their capital and life sentences. The judge had delivered the verdicts in those cases only after SC took judicial notice of the same.",
    "img": "https://static.toiimg.com/photo/msid-127897247,imgsize-57100.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/india/judges-reserving-verdicts-for-years-an-ailment-supreme-court/articleshow/127897253.cms",
    "time": "2026-02-04T00:02:40.000Z"
  },
  {
    "cat": "Politics",
    "title": "Taekwondo master to be Manipur CM, may get 2 deputies",
    "desc": "Keen to project a message of ethnic reconciliation in the north-eastern state, which was rocked by Meitei versus Kuki violence, BJP is considering appointing two deputy CMs — one each from the Kuki and Naga communities, with Singh being a Meitei. Nemcha Kipgen, a Kuki figure and former minister, is likely to be one of the deputy CMs.",
    "img": "https://static.toiimg.com/photo/msid-127897166,imgsize-105210.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/india/taekwondo-master-to-be-manipur-cm-may-get-2-deputies/articleshow/127897153.cms",
    "time": "2026-02-03T23:51:42.000Z"
  },
  {
    "cat": "Politics",
    "title": "Duty relief kicks in, now you can shop a bit more while abroad",
    "desc": "Used personal effects like clothes and travel souvenirs are duty-free. New goods like gifts purchases abroad qualify according to new limits. Goods above the duty-free limit are dutiable under normal customs provisions unless specifically exempted by the law. These allowances apply only to goods carried on the passenger’s person or in bona fide baggage.",
    "img": "https://static.toiimg.com/photo/msid-127897144,imgsize-41518.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/india/duty-relief-kicks-in-now-you-can-shop-a-bit-more-while-abroad/articleshow/127897133.cms",
    "time": "2026-02-03T23:39:13.000Z"
  },
  {
    "cat": "Politics",
    "title": "Grounded 787’s fuel control switch lock satisfactory: Govt",
    "desc": "The first grounding occurred on Feb 1 after a malfunction was registered by the crew of B787 (VT-ANX) during engine start to operate flight AI-132 from London to Bengaluru. The incident was critical as the fuel control switch locking mechanism has been at the centre of the investigation into the June 12 Air India Ahmedabad crash.",
    "img": "https://static.toiimg.com/photo/msid-127897115,imgsize-84208.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/india/grounded-787s-fuel-control-switch-lock-satisfactory-govt/articleshow/127897096.cms",
    "time": "2026-02-03T23:30:56.000Z"
  },
  {
    "cat": "Politics",
    "title": "Sustained PM2.5 exposure ups depression risk: Study",
    "desc": "The burden was highest among urban metro residents, people aged 40-49 years, and those from lower-income groups. Regionally, pollution-linked depression showed stronger associations in eastern India, while anxiety was more prominent in the western region. Risks also peaked during the post-monsoon season, when pollution levels typically rise. he study went beyond overall PM2.5 levels to examine individual chemical constituents of air pollution.",
    "img": "https://static.toiimg.com/photo/msid-127897076,imgsize-20120.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/india/sustained-pm2-5-exposure-ups-depression-risk-study/articleshow/127897069.cms",
    "time": "2026-02-03T23:20:36.000Z"
  },
  {
    "cat": "Business",
    "title": "Dhoot Transmission files confidential draft papers; aims to raise USD 250 mn via IPO",
    "desc": "Backed by private equity major Bain Capital, the proposed IPO will comprise a fresh issue of equity shares along with an offer for sale (OFS) by existing investors, while the promoters will not sell any stake through the OFS, sources said",
    "img": "https://via.placeholder.com/600x400?text=News",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/business/Industry/dhoot-transmission-files-confidential-draft-papers-aims-to-raise-usd-250-mn-via-ipo/article70589304.ece",
    "time": "2026-02-03T22:59:11.000Z"
  },
  {
    "cat": "Business",
    "title": "Markets celebrates as signs of clarity emerge from U.S.",
    "desc": "The Indian rupee emerged as the best-performing Asian currency on Tuesday (February 3. 2026), registering a record gain of 117 paise or 1.28% in a single trading session to settle at 90.32 against the U.S. dollar",
    "img": "https://via.placeholder.com/600x400?text=News",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/business/markets/markets-celebrates-as-signs-of-clarity-emerge-from-us/article70588179.ece",
    "time": "2026-02-03T22:41:34.000Z"
  },
  {
    "cat": "Business",
    "title": "Agriculture, dairy shielded in India-US deal; trade pact in weeks",
    "desc": "As a result, cereals, maize, soybean and genetically modified food may be kept out of the bilateral trade agreement, which has been in the works since last Feb. Goyal said that Modi had managed to secure a very good deal for India, which was better than what US had offered to some other competing countries. Indian and American officials are currently engaged in drafting a joint statement which is expected to be finalised in the next few days.",
    "img": "https://static.toiimg.com/photo/msid-127894788,imgsize-56434.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/agricultre-dairy-shielded-in-india-us-deal-trade-pact-in-weeks/articleshow/127894789.cms",
    "time": "2026-02-03T21:50:42.000Z"
  },
  {
    "cat": "Sports",
    "title": "MCC brings in 73 law changes, makes final over mandatory",
    "desc": "The MCC said the ‘new edition of the Laws of Cricket’, the first since 2022, has been drafted in to ensure laws are ‘up to date and fit for the modern game and that they should be as inclusive as possible’",
    "img": "https://via.placeholder.com/600x400?text=News",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/sport/cricket/mcc-brings-in-73-law-changes-makes-final-over-mandatory/article70589140.ece",
    "time": "2026-02-03T21:32:06.000Z"
  },
  {
    "cat": "Business",
    "title": "India-US trade deal: Elated exporters eyeing discount cuts on orders",
    "desc": "Most exporters spent early Tuesday with buyers discussing the way forward, especially with garment orders for the next season being finalised. “We are in talks with our buyers and they are very happy. The timing of the announcement has been very good as orders for the next season were being finalised. The future is looking very bright, and we need to build scale, focus on expansion and skilling to take advantage of it,” said Sudhir Sekhri of Trendsetters, an exporter of womenswear.",
    "img": "https://static.toiimg.com/photo/msid-127894440,imgsize-32894.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/india-us-trade-deal-elated-exporters-eyeing-discount-cuts-on-orders/articleshow/127894420.cms",
    "time": "2026-02-03T21:13:10.000Z"
  },
  {
    "cat": "Business",
    "title": "Pharma companies await clarity, eye a dose of stability in India-US deal",
    "desc": "With the US accounting for nearly 35% of India’s overall pharma shipments of over $30 billion in FY24-25, the move is expected to bolster growth prospects and pipeline visibility. A potential India-US trade deal offers long-awaited stability for the domestic pharma sector, which plays a critical role in supplying affordable medicines to the US, industry experts told TOI.",
    "img": "https://static.toiimg.com/photo/msid-127894340,imgsize-104968.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/pharma-companies-await-clarity-eye-a-dose-of-stability-in-india-us-deal/articleshow/127894346.cms",
    "time": "2026-02-03T20:45:21.000Z"
  },
  {
    "cat": "Business",
    "title": "India–US trade deal: Textile, leather players see revival in volumes",
    "desc": "Textile and apparel exporters are now expecting an increased sourcing by global brands as India will now enjoy one of the lowest tariff regimes among major Asian manufacturing hubs, with a marginal advantage over competitors, such as Bangladesh, Sri Lanka, Vietnam and China. The tariff relief is expected to create a level-playing field, particularly for small and medium exporters in clusters such as Surat, Gurugram and Tirupur.",
    "img": "https://static.toiimg.com/photo/msid-127894332,imgsize-70446.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/indiaus-trade-deal-textile-leather-players-see-revival-in-volumes/articleshow/127894316.cms",
    "time": "2026-02-03T20:39:22.000Z"
  },
  {
    "cat": "Politics",
    "title": "Air India plane flown afterphysical checks, no abnormal parameters noticed: DGCA",
    "desc": "The fuel control switch of the left engine of the Dreamliner aircraft VT-ANX, which operated the flight AI132 that had more than 200 people on board, did not latch on the 'RUN' position twice during the engine start at London Heathrow airport, but was properly locked in the 'RUN' position on the third attempt",
    "img": "https://via.placeholder.com/600x400?text=News",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/national/ai-flight-with-fuel-switch-issue-flew-after-physical-checks-found-no-abnormal-parameters-says-dgca/article70588170.ece",
    "time": "2026-02-03T20:33:20.000Z"
  },
  {
    "cat": "Business",
    "title": "After tariff cut, exporters of seafood eye recovery in US",
    "desc": "Seafood Exporters Association of India (SEAI) said it expects shipments to rebound following the conclusion of the India-US trade deal and the reduction of tariffs to 18%. “We are confident that with the conclusion of the trade deal and lowering of tariffs to 18%, the quantum of export of seafood from India to the US will show an increase and soon reach back to the previous levels,” the association said. SEAI also welcomed the role played by govt in finalising the agreement.",
    "img": "https://static.toiimg.com/photo/msid-127894302,imgsize-134758.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/after-tariff-cut-exporters-of-seafood-eye-recovery-in-us/articleshow/127894135.cms",
    "time": "2026-02-03T20:30:12.000Z"
  },
  {
    "cat": "Business",
    "title": "Time to pause? RBI may keep rates unchanged at MPC meet",
    "desc": "The RBI cut rates in Dec after the MPC placed greater weight on inflation slipping below the lower bound of the flexible inflation targeting framework. With inflation now expected to move higher, including under the new base-year series to be released from Feb 12, economists see limited scope for further easing. Growth is also expected to slow and settle in the 6.7-7% range in FY27, close to the Economic Survey’s estimate of potential growth at 7%.",
    "img": "https://static.toiimg.com/photo/msid-127894116,imgsize-80544.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/time-to-pause-rbi-may-keep-rates-unchanged-at-mpc-meet/articleshow/127894084.cms",
    "time": "2026-02-03T19:45:13.000Z"
  },
  {
    "cat": "Business",
    "title": "India-US pact removes uncertainty for businesses",
    "desc": "Arvind Shrivastava, secretary, department of revenue, said the deal would deepen trade ties between 2 of the world’s largest economies. He said it would create fresh opportunities for India’s labour-intensive and manufacturing sectors in the US market, while also giving a push to collaboration in high and advanced technology areas and “give impetus to mutually beneficial collaboration in high and advanced technology sectors”, he said.",
    "img": "https://static.toiimg.com/photo/msid-127894085,imgsize-43248.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/govt-officials-india-us-pact-removes-uncertainty-for-businesses/articleshow/127894082.cms",
    "time": "2026-02-03T19:44:09.000Z"
  },
  {
    "cat": "Politics",
    "title": "London’s Veeraswamy restaurant: carrying curry afar",
    "desc": "London’s Veeraswamy restaurant was founded by Edward Palmer, who promoted Veerasawmy (that was the original, and colonial spelling) & Co. in 1896 chiefly to export curry powder to the U.K., which was sold under the brand name Nizam",
    "img": "https://th-i.thgim.com/public/news/national/tamil-nadu/qotqki/article70588944.ece/alternates/LANDSCAPE_1200/Screenshot%202026-02-03%20at%206.38.31%E2%80%AFPM.png",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/cities/chennai/london-veeraswamy-restaurant-carrying-curry-afar/article70588845.ece",
    "time": "2026-02-03T19:42:54.000Z"
  },
  {
    "cat": "Sports",
    "title": "Solely focussed on winning T20WC, trust security: Marsh offers dead bat on T20WC controversies",
    "desc": "“I don’t have any comment on that at this point. We are going to the World Cup to just focus on what we are doing, we will let that stuff take care of itself,” he responded when asked about his thoughts on Pakistan’s boycott of the India game on February 15 in Colombo",
    "img": "https://th-i.thgim.com/public/incoming/hw12rc/article70589126.ece/alternates/LANDSCAPE_1200/Pakistan_Australia_Cricket_92494.jpg",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/sport/cricket/solely-focussed-on-winning-t20wc-trust-security-marsh-offers-dead-bat-on-t20wc-controversies/article70589111.ece",
    "time": "2026-02-03T19:41:52.000Z"
  },
  {
    "cat": "Business",
    "title": "India-US trade deal: ‘Joint statement to be ready in a few days,’ says Piyush Goyal",
    "desc": "After Trump and Modi went public, officials have been engaged on the next steps. Commerce and industry minister Piyush Goyal said on Tuesday that a joint statement will be released shortly. Officials indicated that it should be ready in a few days, and will be followed by the vetting of the agreement before it is signed.",
    "img": "https://static.toiimg.com/photo/msid-127894051,imgsize-82204.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/india-us-trade-deal-joint-statement-to-be-ready-in-a-few-days-says-piyush-goyal/articleshow/127894030.cms",
    "time": "2026-02-03T19:39:23.000Z"
  },
  {
    "cat": "Sports",
    "title": "Cummins says desire to play all Tests also reason behind decision to skip T20WC",
    "desc": "Cummins has been dealing with the back injury since Australia's tour of the the West Indies last July and although he is feeling \"really good\" right now, he decided to skip the tournament starting February 7 after a scan",
    "img": "https://th-i.thgim.com/public/incoming/muf272/article70589125.ece/alternates/LANDSCAPE_1200/Australia_England_Cricket_69803.jpg",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/sport/cricket/cummins-says-desire-to-play-all-tests-also-reason-behind-decision-to-skip-t20wc/article70589110.ece",
    "time": "2026-02-03T19:38:05.000Z"
  },
  {
    "cat": "Business",
    "title": "India-US trade pact: Exports to US may rise, add to India’s growth momentum",
    "desc": "The Aug decision by US President Donald Trump to impose stiff tariffs on India for purchasing Russian oil had stunned policymakers and exporters. Financial markets turned choppy and triggered unease about the trajectory of growth. But the economy remained resilient and growth momentum robust as it navigated the turbulent period.",
    "img": "https://static.toiimg.com/photo/msid-127894028,imgsize-32894.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/india-us-trade-pact-exports-to-us-may-rise-add-to-indias-growth-momentum/articleshow/127894015.cms",
    "time": "2026-02-03T19:37:16.000Z"
  },
  {
    "cat": "Business",
    "title": "Rupee logs best 1-day gain in over seven years",
    "desc": "The rupee jumped 124 paise to 90.27 against the dollar, its strongest single-day gain in seven years and the best since late 2018. The currency had closed at 91.51 in the previous session and has strengthened 165 paise over two days. The rebound followed a recent record low of 91.99, when corporate dollar hedging and concerns over capital outflows had weighed on the currency.",
    "img": "https://static.toiimg.com/photo/msid-127893876,imgsize-74874.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/power-rally-rupee-logs-best-1-day-gain-in-over-seven-years/articleshow/127893863.cms",
    "time": "2026-02-03T19:30:44.000Z"
  },
  {
    "cat": "Business",
    "title": "India-US trade deal: Steep tariffs to stay for steel, copper and aluminium",
    "desc": "Within this landscape, Tata Steel’s Indian operations do not export to the US, though its UK unit does. In contrast, JSW Steel, with facilities in Ohio and Texas, produces steel locally, shielding it from import tariffs. Hindalco exports negligible aluminium and no copper from India to the US due to strong domestic demand.",
    "img": "https://static.toiimg.com/photo/msid-127893852,imgsize-1860101.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/india-us-trade-deal-steep-tariffs-to-stay-for-steel-copper-and-aluminium/articleshow/127893846.cms",
    "time": "2026-02-03T19:28:25.000Z"
  },
  {
    "cat": "Business",
    "title": "Foreign funds likely to drive into India again",
    "desc": "So far in 2026, foreign portfolio investors (FPIs) have net sold stocks worth nearly Rs 35,000 crore in the Indian market. This comes on top of the Rs 1.7 lakh crore worth of stocks net offloaded in 2025. The sell-off, in turn, put pressure on the rupee. Despite strong central govt intervention, the rupee had depreciated over 6% since the start of 2025.",
    "img": "https://static.toiimg.com/photo/msid-127893778,imgsize-298932.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/foreign-funds-likely-to-drive-into-india-again/articleshow/127893704.cms",
    "time": "2026-02-03T19:23:05.000Z"
  },
  {
    "cat": "Business",
    "title": "Dalal Street blows 'Trump'et with 2000-point salute to trade deal",
    "desc": "The feel-good rally that followed lifted sensex by nearly 4,200 points (5.2%) in early trades but soon profit booking at higher levels pulled it down a bit. After a steady session, sensex closed 2.5% up. On the NSE, Nifty too treaded a similar path and closed 639 points (2.6%) up at 25,728 points. According to A Balasubramanian, MD & CEO, Aditya Birla Sun Life Mutual Fund, the announcements about the India-US trade deal removed a key overhang for Indian markets.",
    "img": "https://static.toiimg.com/photo/msid-127893799,imgsize-1386357.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/business/india-business/dalal-street-blows-trumpet-with-2000-point-salute-to-trade-deal/articleshow/127893673.cms",
    "time": "2026-02-03T19:21:23.000Z"
  },
  {
    "cat": "Sports",
    "title": "Delhi Capitals storm into 4th consecutive final with dominant win",
    "desc": "Delhi Capitals cruised into their fourth straight WPL final with a dominant seven-wicket win over Gujarat Giants. After restricting Gujarat to 168/7, led by Chinelle Henry’s 3/35, DC chased the target in 15.4 overs. Shafali Verma and Lizelle Lee starred up top before Jemimah Rodrigues sealed a final clash with RCB.",
    "img": "https://static.toiimg.com/photo/msid-127891788,imgsize-33270.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/wpl/wpl-2026-delhi-capitals-storm-into-4th-consecutive-final-with-dominant-win-over-gujarat-giants/articleshow/127891592.cms",
    "time": "2026-02-03T17:44:43.000Z"
  },
  {
    "cat": "Sports",
    "title": "Lauren Bell spearheads RCB’s march to WPL final",
    "desc": "The 25-year-old pacer from England has been on target from the very start of the fourth season of the Women’s Premier League. Having picked up 12 wickets and bowled 116 dot balls in eight matches, the leader of the Bengaluru outfit’s bowling attack reflects on a fabulous campaign ahead of the final on Thursday",
    "img": "https://th-i.thgim.com/public/sport/gk242f/article70588975.ece/alternates/LANDSCAPE_1200/BELL.jpg",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/sport/in-the-swing-of-things-lauren-bell-spearheads-rcbs-march-to-wpl-final/article70588967.ece",
    "time": "2026-02-03T17:38:52.000Z"
  },
  {
    "cat": "Politics",
    "title": "A.P. to set up palliative centres in all teaching hospitals in State, says Minister",
    "desc": "Satya Kumar Yadav says the government is also considering the idea of expanding cancer care services to every district headquarters; notes that the number of cancer cases has seen gradual increase in Andhra Pradesh from 25,487 in 2020 to 35,546 in 2025",
    "img": "https://via.placeholder.com/600x400?text=News",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/national/andhra-pradesh/ap-to-set-up-palliative-centres-in-all-teaching-hospitals-in-state-says-minister/article70588411.ece",
    "time": "2026-02-03T17:38:09.000Z"
  },
  {
    "cat": "Politics",
    "title": "Transform A.P. into largest natural farming hub, CM tells officials",
    "desc": "Chandrababu Naidu directs officials to develop a Cocoa City over 500 acres in Eluru district; announces that registration of aquaculture activities will be made mandatory; suggests organising crop-festivals in various regions to promote awareness of different crops and boost tourism",
    "img": "https://via.placeholder.com/600x400?text=News",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/national/andhra-pradesh/transform-ap-into-largest-natural-farming-hub-cm-tells-officials/article70588534.ece",
    "time": "2026-02-03T17:32:00.000Z"
  },
  {
    "cat": "Business",
    "title": "Why the government has increased capital spending for the defence sector",
    "desc": "The government has announced a record ₹7,84,678 crore for defence in the FY2026-27 Union Budget, addressing urgent military needs amid geopolitical tensions. The increased funding aims to enhance domestic capabilities and support the Aatmanirbhar Bharat initiative",
    "img": "https://th-i.thgim.com/public/incoming/mjl0fm/article70588907.ece/alternates/LANDSCAPE_1200/AFP_94JF8XV.jpg",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/business/budget/why-the-government-has-increased-capital-spending-for-the-defence-sector/article70587496.ece",
    "time": "2026-02-03T17:10:41.000Z"
  },
  {
    "cat": "Sports",
    "title": "Willow by Cricbuzz to stream Team USA T20 WC matches free on YouTube",
    "desc": "Willow by Cricbuzz has announced major updates for the 2026 season, including free streaming of all four Team USA matches at the ICC Men’s T20 World Cup on YouTube for the first time. The platform has also partnered with Jomboy Media for creator-led alternate telecasts and unveiled a revamped, faster viewing experience across its apps and devices.",
    "img": "https://static.toiimg.com/photo/msid-127890697,imgsize-11296.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/icc-mens-t20-world-cup/willow-by-cricbuzz-to-stream-team-usa-t20-world-cup-2026-matches-free-on-youtube/articleshow/127890058.cms",
    "time": "2026-02-03T16:49:44.000Z"
  },
  {
    "cat": "Politics",
    "title": "GSI to probe land subsidence in Godavari delta in Andhra Pradesh",
    "desc": "The Water Resource Department has roped in the experts to fix the scientific reasons for the land subsidence, factors for the defunct 350-long irrigation drains in the Central Delta thriving with oil and natural gas exploration activities.",
    "img": "https://th-i.thgim.com/public/incoming/wdupsu/article70588692.ece/alternates/LANDSCAPE_1200/10237_3_2_2026_18_29_45_1_GSI1.JPEG",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/national/andhra-pradesh/gsi-to-probe-land-subsidence-in-godavari-delta-in-andhra-pradesh/article70587830.ece",
    "time": "2026-02-03T16:10:44.000Z"
  },
  {
    "cat": "Politics",
    "title": "UDF finalising candidate list for Kottayam ahead of Statewide rally",
    "desc": "The UDF aims to finalise candidates, aligning with Leader of the Opposition V.D. Satheesan’s rally on February 24. Amid ongoing seat-sharing disputes, particularly in Changanassery and Ettumanur, UDF leaders are prioritising candidates with community support to reclaim lost seats.",
    "img": "https://via.placeholder.com/600x400?text=News",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/national/kerala/udf-finalising-candidate-list-for-kottayam-ahead-of-statewide-rally/article70588104.ece",
    "time": "2026-02-03T15:41:34.000Z"
  },
  {
    "cat": "Politics",
    "title": "SFI leaders ‘abducted’ in Tirupati",
    "desc": "The leaders were on their way to the Collectorate to join the protest against alleged irregularities of Mohan Babu University, when nearly 30 persons reportedly attacked SFI district general secretary S. Akbar and the federation’s SVU students’ union leader Vinod",
    "img": "https://th-i.thgim.com/public/incoming/z2383q/article70588497.ece/alternates/LANDSCAPE_1200/10215_3_2_2026_20_19_50_1_WHATSAPPIMAGE2026_02_03AT81001PM.JPEG",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/national/andhra-pradesh/sfi-leaders-abducted-in-tirupati/article70588219.ece",
    "time": "2026-02-03T15:36:00.000Z"
  },
  {
    "cat": "Sports",
    "title": "Gautam's gambit! India has a tailor-made team to win back-to-back T20 World Cups",
    "desc": "In Jasprit Bumrah, Arshdeep Singh, Varun Chakravarthy, Hardik Pandya and Axar Patel, India arguably have the best quartet of bowlers at the T20 World Cup. Not to forget, Kuldeep Yadav might have to wait for his chances and the vastly improved Shivam Dube is no pushover. The Suryakumar Yadav-led team looks dangerous not just on paper but has also walked the talk on the field.",
    "img": "https://static.toiimg.com/photo/msid-127889056,imgsize-134086.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/icc-mens-t20-world-cup/gautams-gambit-india-has-a-tailor-made-team-to-win-back-to-back-t20-world-cups/articleshow/127888731.cms",
    "time": "2026-02-03T15:14:34.000Z"
  },
  {
    "cat": "Sports",
    "title": "AFI raises bar for CWG selection",
    "desc": "The Athletics Federation of India has set extremely high qualification standards for the 2026 Commonwealth Games, with athletes in 17 events required to match or break national records. With a reduced squad size, even record holders face challenges. The Federation Cup will be the final trials, though selectors retain discretion to pick medal prospects.",
    "img": "https://static.toiimg.com/photo/msid-127888366,imgsize-38060.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/more-sports/athletics/national-records-may-not-be-enough-afi-raises-bar-for-commonwealth-games-2026-selection/articleshow/127887893.cms",
    "time": "2026-02-03T14:22:23.000Z"
  },
  {
    "cat": "World",
    "title": "Images of Zohran Mamdani and his mother Mira Nair with Jeffrey Epstein are AI-generated",
    "desc": "The images originated on an X account labelled as parody after a huge tranche of new Epstein files was released by the Justice Department. They are clearly watermarked as AI and other elements they contain do not add up.",
    "img": "https://th-i.thgim.com/public/incoming/tq3sn6/article70587447.ece/alternates/LANDSCAPE_1200/Justice_Department_Jeffrey_Epstein_80852.jpg",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/international/fact-focus-images-of-nyc-mayor-with-jeffrey-epstein-are-ai-generated-heres-how-we-know/article70587428.ece",
    "time": "2026-02-03T13:33:18.000Z"
  },
  {
    "cat": "Sports",
    "title": "Bhambri scripts history, becomes first Indian after Rohan Bopanna to...",
    "desc": "Yuki Bhambri climbed to a career-high world No. 20 in the ATP doubles rankings, becoming the first Indian since Rohan Bopanna to enter the Top 20. The rise follows strong performances, including a solid Australian Open run, a US Open semifinal in 2025, and his maiden ATP 500 title in Dubai.",
    "img": "https://static.toiimg.com/photo/msid-127887403,imgsize-80494.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/tennis/top-stories/tennis-star-yuki-bhambri-scripts-history-becomes-first-indian-after-rohan-bopanna-to-/articleshow/127887292.cms",
    "time": "2026-02-03T13:31:58.000Z"
  },
  {
    "cat": "Sports",
    "title": "Unsold in IPL, Australia great joins PSL team for debut campaign",
    "desc": "Former Australia captain Steve Smith has signed with PSL newcomers Sialkot Stallionz for the 2026 season, marking his first appearance in the league. Signed directly under league rules, Smith is expected to play a key leadership role. Despite going unsold in the IPL, he remains a top T20 performer after impressing in the Big Bash League.",
    "img": "https://static.toiimg.com/photo/msid-127886978,imgsize-15692.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/news/unsold-in-ipl-australia-great-joins-new-psl-team-for-debut-campaign-in-pakistan-super-league/articleshow/127886469.cms",
    "time": "2026-02-03T13:13:37.000Z"
  },
  {
    "cat": "Sports",
    "title": "Controversy in Pakistan! Umpire under fire for Connolly dismissal",
    "desc": "Australia’s 3-0 T20 series loss to Pakistan sparked controversy after replays showed Cooper Connolly was wrongly stumped in the third match. Wicketkeeper Khawaja Nafay broke the stumps with the glove not holding the ball, breaching ICC rules. The error went unchecked, angering fans and raising concerns over umpiring and sportsmanship despite Pakistan’s dominant win.",
    "img": "https://static.toiimg.com/photo/msid-127885919,imgsize-31400.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/news/controversy-in-pakistan-umpire-under-fire-for-australia-batter-cooper-connollys-dismissal-watch/articleshow/127885496.cms",
    "time": "2026-02-03T12:25:55.000Z"
  },
  {
    "cat": "Sports",
    "title": "'India vs Pakistan presented as war now,' says J&amp;K CM Omar Abdullah",
    "desc": "Omar Abdullah, the Chief Minister of Jammu and Kashmir, expressed disappointment over Pakistan's decision to withdraw from the T20 World Cup match against India, underscoring the troubling overlap of sports and politics. He pointed out that the hype surrounding India-Pakistan games often leads to unnecessary disputes.",
    "img": "https://static.toiimg.com/photo/msid-127885467,imgsize-82128.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/icc-mens-t20-world-cup/india-vs-pakistan-t20-world-cup-omar-abdullah/articleshow/127885438.cms",
    "time": "2026-02-03T12:07:37.000Z"
  },
  {
    "cat": "Tech",
    "title": "France summons Elon Musk for ‘voluntary interview’, raids X offices",
    "desc": "Prosecutors filed a request for “voluntary interviews” of Elon Musk and Linda Yaccarino, CEO of X from 2023 to 2025, scheduled for April 20; employees of the platform X have also been summoned that same week in April to be heard as witnesses",
    "img": "https://th-i.thgim.com/public/news/cities/Delhi/2eerbe/article70587325.ece/alternates/LANDSCAPE_1200/2025-03-20T143340Z_580507215_RC2TFCA9BECE_RTRMADP_3_INDIA-X-CENSORSHIP.jpg",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/sci-tech/technology/france-summons-elon-musk-for-voluntary-interview-raids-x-offices/article70587218.ece",
    "time": "2026-02-03T12:02:08.000Z"
  },
  {
    "cat": "Sports",
    "title": "Boxer loses wig during fight, blames mother's shampoo",
    "desc": "American boxer Jarrell Miller won his heavyweight bout at Madison Square Garden but lost his toupee mid-fight after taking punches from Kingsley Ibeh. Spotting it come loose, he laughed and threw it into the crowd, then blamed his sudden hair loss on shampoo at his mother’s house, calling the moment embarrassing but funny.",
    "img": "https://static.toiimg.com/photo/msid-127885335,imgsize-76506.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/more-sports/others/watch-boxer-loses-wig-during-fight-blames-mothers-shampoo/articleshow/127885170.cms",
    "time": "2026-02-03T12:01:35.000Z"
  },
  {
    "cat": "Sports",
    "title": "Another Indian! After Pragg, Norway Chess 2026 reveals 4th participant",
    "desc": "Reigning world champion Gukesh Dommaraju has been confirmed as the fourth participant for Norway Chess 2026, joining fellow Indian R Praggnanandhaa. The youngest world champion in history, Gukesh returns after a strong 2025 showing and a memorable win over Magnus Carlsen, highlighting India’s growing dominance in world chess.",
    "img": "https://static.toiimg.com/photo/msid-127884498,imgsize-26824.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/chess/another-indian-after-r-praggnanandhaa-norway-chess-reveals-fourth-participant-for-2026-event/articleshow/127884358.cms",
    "time": "2026-02-03T11:24:02.000Z"
  },
  {
    "cat": "Sports",
    "title": "Now representing USA, Ranjane looking to play against ‘best buddy’ SKY",
    "desc": "Former Mumbai allrounder Shubham Ranjane, now representing USA, is reliving nostalgic moments after returning to Mumbai for the T20 World Cup. Excited to play at Wankhede, meet close friend Suryakumar Yadav, and face India, Ranjane calls it a proud, emotional homecoming as family cheers him on.",
    "img": "https://static.toiimg.com/photo/msid-127884206,imgsize-61990.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/icc-mens-t20-world-cup/now-representing-usa-shubham-ranjane-looking-to-play-against-best-buddy-suryakumar-yadav-at-t20-world-cup/articleshow/127883506.cms",
    "time": "2026-02-03T11:11:03.000Z"
  },
  {
    "cat": "Sports",
    "title": "When India pushed Australia to the edge",
    "desc": "India's 1977/78 tour of Australia saw a remarkable turnaround. After losing the first two Tests, India secured their maiden wins Down Under, including a stunning series-levelling victory. The decider in Adelaide was a nail-biter, with India pushing Australia to the brink before ultimately losing the series 3-2.",
    "img": "https://static.toiimg.com/photo/msid-127882536,imgsize-102520.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/news/the-loss-that-roared-like-a-win-when-india-pushed-australia-to-the-edge-in-adelaide-1978/articleshow/127882099.cms",
    "time": "2026-02-03T09:58:07.000Z"
  },
  {
    "cat": "Sports",
    "title": "'Was ICC sleeping?' Ex-Pakistan star says 'PCB should not back down'",
    "desc": "Former Pakistan cricketer Kamran Akmal has slammed the ICC for urging the PCB to reconsider boycotting the India match at the T20 World Cup. Akmal questioned the ICC's past inaction on political issues affecting cricket between the two nations, including the Asia Cup and India's refusal to play in Pakistan.",
    "img": "https://static.toiimg.com/photo/msid-127882315,imgsize-91944.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/icc-mens-t20-world-cup/was-icc-sleeping-ex-pakistan-star-says-pcb-should-not-back-down-amid-india-boycott-row/articleshow/127882308.cms",
    "time": "2026-02-03T09:49:56.000Z"
  },
  {
    "cat": "Sports",
    "title": "Ishan OUT, Samson IN: India spinner announces playing XI vs USA",
    "desc": "Despite a stellar T20I series, Ishan Kishan was surprisingly omitted from Yuzvendra Chahal's preferred XI for India's T20 World Cup opener. Chahal opted for the struggling Sanju Samson to open alongside Abhishek Sharma, a decision that raises eyebrows given Kishan's dominant recent form.",
    "img": "https://static.toiimg.com/photo/msid-127881502,imgsize-76628.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/icc-mens-t20-world-cup/ishan-kishan-out-sanju-samson-in-india-spinner-announces-playing-xi-vs-usa-in-t20-world-cup/articleshow/127881497.cms",
    "time": "2026-02-03T09:09:57.000Z"
  },
  {
    "cat": "Sports",
    "title": "'Effort to win trophies will always continue': Rohit after being conferred Padma Shri",
    "desc": "Rohit Sharma, honored with the Padma Shri, expressed deep gratitude for the prestigious civilian award, calling it a momentous occasion for his family. He reaffirmed his unwavering dedication to securing victories for India on the cricket field. This recognition celebrates his significant contributions as both a player and captain, marking a distinguished chapter in his illustrious career.",
    "img": "https://static.toiimg.com/photo/msid-127880808,imgsize-74856.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/news/effort-to-win-trophies-for-my-country-will-always-continue-rohit-sharma-after-being-conferred-padma-shri-watch/articleshow/127880792.cms",
    "time": "2026-02-03T08:36:17.000Z"
  },
  {
    "cat": "Sports",
    "title": "India to host shooting's Asian Olympic qualifying championship in 2027",
    "desc": "The eight slots in the Asian competition will be in addition to the 12 quota places that will be on offer in the World Cup (Rifle/Pistol/Shotgun) from April 21 to 30 next year, also to be held in Delhi",
    "img": "https://th-i.thgim.com/public/incoming/9riwdk/article70586509.ece/alternates/LANDSCAPE_1200/vbk-stock-shooting-rifle-pistol-competition-iStock-2188562382.jpg",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/sport/other-sports/india-to-host-shootings-asian-olympic-qualifying-championship-next-year/article70586484.ece",
    "time": "2026-02-03T07:42:07.000Z"
  },
  {
    "cat": "Sports",
    "title": "Samson’s slide opens door as Kishan storms into India’s T20 WC plans",
    "desc": "India's T20 juggernaut faces a crucial selection dilemma ahead of the 2026 World Cup, with Sanju Samson's recent form under scrutiny. Despite a strong past record, his struggles against New Zealand have opened the door for Ishan Kishan's impressive resurgence, creating a headache for the management as they aim to defend their title.",
    "img": "https://static.toiimg.com/photo/msid-127879099,imgsize-75380.cms",
    "src": "indiatimes.com",
    "url": "https://timesofindia.indiatimes.com/sports/cricket/icc-mens-t20-world-cup/form-vs-faith-sanju-samsons-slide-opens-door-as-ishan-kishan-storms-into-indias-t20-world-cup-plans/articleshow/127878765.cms",
    "time": "2026-02-03T07:12:36.000Z"
  },
  {
    "cat": "World",
    "title": "Cuba confirms ‘communications’ with U.S., but says no negotiations yet",
    "desc": "Donald Trump, on February 2, claimed the United States was in talks with “the highest people” in communist Cuba and that he expected to “make a deal” with its leadership, without saying what a deal might look like",
    "img": "https://th-i.thgim.com/public/incoming/8h0nd7/article70585904.ece/alternates/LANDSCAPE_1200/2026-02-02T210835Z_530100915_RC2VDJA0NI74_RTRMADP_3_CUBA-USA.JPG",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/international/cuba-confirms-communications-with-us-but-says-no-negotiations-yet/article70585893.ece",
    "time": "2026-02-03T03:28:05.000Z"
  },
  {
    "cat": "World",
    "title": "Drone attack targets strategic northeast Congo city, authorities say, blaming M23",
    "desc": "The government of ⁠Tshopo province, where Kisangani is located, said in a statement on Sunday (February 1, 2026) that the drones attempted to strike Bangoka International Airport between ​early Saturday (January 31, 2026) and early Sunday (February 1, 2026) ⁠but were shot down before reaching their target",
    "img": "https://th-i.thgim.com/public/incoming/gg8sbr/article70468492.ece/alternates/LANDSCAPE_1200/2025-12-11T194833Z_458289501_RC2DEIAWK9L4_RTRMADP_3_CONGO-SECURITY.JPG",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/international/drone-attack-targets-strategic-northeast-congo-city-authorities-say-blaming-m23/article70585089.ece",
    "time": "2026-02-03T02:25:27.000Z"
  },
  {
    "cat": "Sports",
    "title": "Uzbekistan's Abdusattorov wins Tata Steel Masters title, Gukesh best Indian at joint eighth",
    "desc": "Gukesh drew with Vincent Keymer of Germany in the final round to end as the top performing Indian on 6.5 points. But, his fifty per cent score was below par and the Indian ace slipped below the 2750 rating mark",
    "img": "https://via.placeholder.com/600x400?text=News",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/sport/other-sports/uzbekistans-abdusattorov-wins-tata-steel-masters-title-gukesh-best-indian-at-joint-eighth/article70584839.ece",
    "time": "2026-02-02T19:23:45.000Z"
  },
  {
    "cat": "Sports",
    "title": "Tilak Varma makes solid 38, Jagadeesan's ton shines in India A's win over USA in warm-up game",
    "desc": "Priyansh Arya (28 in 13 balls, with four boundaries and two sixes) played a fiery cameo to start the innings with a 43-run stand with Jagadeesan, who went on to make 104 in 55 balls, with 11 fours and five sixes",
    "img": "https://via.placeholder.com/600x400?text=News",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/sport/cricket/tilak-varma-makes-solid-38-jagadeesans-ton-shines-in-india-as-win-over-usa-in-warm-up-game/article70584831.ece",
    "time": "2026-02-02T19:03:14.000Z"
  },
  {
    "cat": "Business",
    "title": "Rise in southern States’ share in devolution of funds provides no relief to Tamil Nadu",
    "desc": "The share of Tamil Nadu, which was 4.079% in the 15th FC, rose to 4.097% now, accounting for a rate of increase of only 0.44%; as part of horizontal devolution, the weights assigned to the criteria of area, demographic performance and per-capita GSDP (Gross State Domestic Product) have reduced affecting States like T.N and Kerala",
    "img": "https://th-i.thgim.com/public/incoming/f9g835/article70584821.ece/alternates/LANDSCAPE_1200/vjkvg-budget%204.JPG",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/business/budget/rise-in-southern-states-share-in-devolution-of-funds-provides-no-relief-to-tamil-nadu/article70583725.ece",
    "time": "2026-02-02T18:54:00.000Z"
  },
  {
    "cat": "World",
    "title": "China's top general probe to 'remove obstacles' in military: state media",
    "desc": "The Defence Ministry said last month it was investigating Mr. Zhang, the Vice Chairman of the powerful Central Military Commission (CMC), as well as Liu Zhenli, Chief of Staff of the CMC's joint staff department, which oversees combat planning",
    "img": "https://th-i.thgim.com/public/incoming/tnvt4r/article70584637.ece/alternates/LANDSCAPE_1200/IMG_China_Navy_Symposium_2_1_NSCN3SVD.jpg",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/international/chinas-top-general-probe-to-remove-obstacles-in-military-state-media/article70584175.ece",
    "time": "2026-02-02T16:52:05.000Z"
  },
  {
    "cat": "Tech",
    "title": "Snowflake and OpenAI make a $200 million bid to corner corporate data intelligence market",
    "desc": "The deal, which integrates OpenAI’s most advanced models directly into Snowflake’s data infrastructure, represents a significant tactical shift for both firms, signalling that the battle for enterprise AI has moved from the chatbox to the database",
    "img": "https://th-i.thgim.com/public/sci-tech/technology/z8x9fo/article70581892.ece/alternates/LANDSCAPE_1200/216db353-3e70-497f-acbf-63f28709817a.png",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/sci-tech/technology/snowflake-and-openai-make-a-200-million-bid-to-corner-corporate-data-intelligence-market/article70581945.ece",
    "time": "2026-02-02T15:21:24.000Z"
  },
  {
    "cat": "World",
    "title": "Gaza’s Rafah crossing makes limited reopening after two-year war",
    "desc": "Israel said the crossing had opened in a test, and the Israeli military agency that controls aid to Gaza said residents could begin crossing Monday. But only a small number of people can cross at first",
    "img": "https://th-i.thgim.com/public/incoming/vp5ejx/article70581517.ece/alternates/LANDSCAPE_1200/Egypt_Mideast_Wars_Gaza_58307.jpg",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/news/international/israel-gaza-rafah-crossing-opening-february-2-2026/article70581484.ece",
    "time": "2026-02-02T14:47:04.000Z"
  },
  {
    "cat": "Entertainment",
    "title": "‘Bheegi Bheegi’: A R Ameen creates a timeless love experience with Dulquer Salmaan and Mrunal Thakur",
    "desc": "‘Bheegi Bheegi’, a dreamy music video, stars Dulquer Salmaan and Mrunal Thakur, and takes you on a romantic journey through alternate realities, mixing retro charm with futuristic flair. AR Ameen and Jasleen Royal has sung the song while A R Rahman has composed it",
    "img": "https://th-i.thgim.com/public/entertainment/movies/7dzjo/article70583567.ece/alternates/LANDSCAPE_1200/Ameen.jpg",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/entertainment/movies/a-r-ameen-a-r-rahman-bheegi-bheegi-dulquer-salmaan-mrunal-thakur-jasleen-royal/article70583386.ece",
    "time": "2026-02-02T14:41:09.000Z"
  },
  {
    "cat": "Sports",
    "title": "ISL 2025-26: FanCode selected as media partner, KPS to handle production",
    "desc": "JioStar, the exclusive broadcast partner of the ISL for the last two seasons and whose parent company owned the league for the last 10 years, lost out, having quoted a financial bid of around ₹5 crore",
    "img": "https://via.placeholder.com/600x400?text=News",
    "src": "thehindu.com",
    "url": "https://www.thehindu.com/sport/football/isl-2025-26-fancode-selected-as-media-partner-kps-to-handle-production/article70583821.ece",
    "time": "2026-02-02T14:20:58.000Z"
  }
];